sudo: false
language: node_js
node_js:
  - "0.12"
cache:
  directories:
  - kbase-extension/static/components
  - node_modules
branches:
  only:
    - develop
    - staging
    - master
    - jupyter
before_install:
  - npm install -g bower
  - npm install -g grunt-cli
script: make && make test