language: node_js
node_js:
  - "0.12"
  - "iojs"
branches:
  only:
    - develop
    - staging
    - master
before_install:
  - git clone git://github.com/kbase/bootstrap
  - sudo pip install -r bootstrap/kb_python_runtime/python-pip-list-narrative
  - npm install -g grunt-cli
script: make && make test